name: C/I Testing.

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5, 3.6, 3.7, 3.8]
        django: [2.2.*, 3.0.*]
        exclude: 
          # exclude python 3.5 with django v3+
          - python: 3.5
            django: 3.0.*

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python}}


    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install django==${{ matrix.django }}
    - name: Test with pytest
      run: |
        cd /home/runner/work/django-crispy-forms/django-crispy-forms/
        make test
