name: isort

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install isort
      run: |
        python -m pip install --upgrade pip
        pip install isort
    - name: run isort
      run: |
        cd crispy_forms
        isort . --check --dif
